/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as BlogsCreate_blogRouteImport } from './routes/blogs/create_blog'
import { Route as BlogsPostIdEditRouteImport } from './routes/blogs/$postId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsCreate_blogRoute = BlogsCreate_blogRouteImport.update({
  id: '/blogs/create_blog',
  path: '/blogs/create_blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsPostIdEditRoute = BlogsPostIdEditRouteImport.update({
  id: '/blogs/$postId/edit',
  path: '/blogs/$postId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs/create_blog': typeof BlogsCreate_blogRoute
  '/blogs/': typeof BlogsIndexRoute
  '/blogs/$postId/edit': typeof BlogsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs/create_blog': typeof BlogsCreate_blogRoute
  '/blogs': typeof BlogsIndexRoute
  '/blogs/$postId/edit': typeof BlogsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs/create_blog': typeof BlogsCreate_blogRoute
  '/blogs/': typeof BlogsIndexRoute
  '/blogs/$postId/edit': typeof BlogsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/blogs/create_blog' | '/blogs/' | '/blogs/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/blogs/create_blog' | '/blogs' | '/blogs/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs/create_blog'
    | '/blogs/'
    | '/blogs/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsCreate_blogRoute: typeof BlogsCreate_blogRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  BlogsPostIdEditRoute: typeof BlogsPostIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/create_blog': {
      id: '/blogs/create_blog'
      path: '/blogs/create_blog'
      fullPath: '/blogs/create_blog'
      preLoaderRoute: typeof BlogsCreate_blogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$postId/edit': {
      id: '/blogs/$postId/edit'
      path: '/blogs/$postId/edit'
      fullPath: '/blogs/$postId/edit'
      preLoaderRoute: typeof BlogsPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsCreate_blogRoute: BlogsCreate_blogRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  BlogsPostIdEditRoute: BlogsPostIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
